### ISSUE TITLE
Face shadow not working

### ISSUE THREAD

**Issue by Wasabihobby234** [festivize/Cheddar#1]
![90C01B0F-6C93-4544-B15A-A414E1E400C0](https://user-images.githubusercontent.com/123320001/213929703-0eee6a2c-ceae-48ad-be83-54c2858930a9.jpeg)

the shadows on everything works fine except for the face. How do I fix this issue?? I’m so close to finishing

**Comment by festivities** [comment]
There's a toggle in the shader options that lets you switch between the body/hair shader and the face shader. Be sure to tick that option for the face material. I recommend watching the tutorial video linked in the README.

**Comment by Wasabihobby234** [comment]
Thank you for the tip! However, I'm having difficulty finding the toggle. Can you tell me where exactly it's located?

**Comment by Wasabihobby234** [comment]
> There's a toggle in the shader options that lets you switch between the body/hair shader and the face shader. Be sure to tick that option for the face material. I recommend watching the tutorial video linked in the README.

I'm having difficulty finding the toggle. Can you tell where exactly it's located?

**Comment by festivities** [comment]
> > There's a toggle in the shader options that lets you switch between the body/hair shader and the face shader. Be sure to tick that option for the face material. I recommend watching the tutorial video linked in the README.
> 
> I'm having difficulty finding the toggle. Can you tell where exactly it's located?

![image](https://user-images.githubusercontent.com/77230051/214222345-da4300ea-5ecc-4f41-8ef9-1194617c9427.png)

**Comment by Levris** [comment]
> ![90C01B0F-6C93-4544-B15A-A414E1E400C0](https://user-images.githubusercontent.com/123320001/213929703-0eee6a2c-ceae-48ad-be83-54c2858930a9.jpeg)
> 
> the shadows on everything works fine except for the face. How do I fix this issue?? I’m so close to finishing

where i can get shadow map textures ?

**Comment by festivities** [comment]
> > ![90C01B0F-6C93-4544-B15A-A414E1E400C0](https://user-images.githubusercontent.com/123320001/213929703-0eee6a2c-ceae-48ad-be83-54c2858930a9.jpeg)
> > the shadows on everything works fine except for the face. How do I fix this issue?? I’m so close to finishing
> 
> where i can get shadow map textures ?

Extremely late reply but common textures used across most characters and weapons are now included in the shader.
